### ISSUE TITLE
Support non-public clouds for Microsoft Azure 

### ISSUE THREAD

**Issue by djj0809** [kedacore/keda#1285]
The resource name and the queue endpoint suffix should be configurable in triggers.

https://github.com/kedacore/keda/blob/57ffd4ee384db38f1169453cb16b31f00eacffa5/pkg/scalers/azure/azure_storage.go#L34-L64

## Task List

- [x] #1921
- [x] #1916
- [x] #1915
- [x] #1917
- [x] #1918
- [x] #1920
- [x] #1919
- [x] https://github.com/kedacore/keda/issues/2733
- [x] https://github.com/kedacore/keda/issues/2734
- [x] https://github.com/kedacore/keda/issues/2735

**Comment by zroubalik** [comment]
@djj0809 are you willing to contribute this?

**Comment by djj0809** [comment]
Would like to, however I’m not quite familiar with go projects...

Zbynek Roubalik <notifications@github.com>于2020年10月23日 周五19:52写道：

**Comment by tomkerkhove** [comment]
Might be something interesting for @ahmelsayed @jeffhollan

**Comment by JonasMatos0** [comment]
Hi, @djj0809 . 

Can you please detail with examples what are the changes related to the Azure National clouds that are not supported on current scaler config implementation?

I'm planning on helping on this issues as soon as I get these details.

**Comment by tomkerkhove** [comment]
Thank you @amirschw!

**Comment by tomkerkhove** [comment]
Re-opening as we didn't cover all Azure scalers yet I think

**Comment by amirschw** [comment]
Indeed. Left to cover:
- Azure Event Bub
- Azure Log Analytics
- Azure Monitor
- Azure Service Bus

Azure Pipelines is only supported in public cloud AFAIK, so it's probably out of scope.

**Comment by tomkerkhove** [comment]
/keep-alive

This is still on-going

**Comment by v-shenoy** [comment]
I can take these up.
