### ISSUE TITLE
Provide e2e test for all scalers (Help Wanted)

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda#2357]
We must provide end-to-end tests for all our scalers.

However, the following are missing:

- [ ] #2220
- [ ] #1529
- [ ] #1526
- [ ] #1524
- [ ] #1525
- [ ] #1528
- [ ] #1527

**Comment by RamCohen** [comment]
Hi @tomkerkhove , will be happy to work on this, but for it to be submitted, the issue of having a secret with the credentials for a GCP service account to use should be resolved (https://github.com/kedacore/keda/pull/2648)

**Comment by v-shenoy** [comment]
@tomkerkhove The Azure Monitor scaler is also missing an e2e test.

**Comment by tomkerkhove** [comment]
Nice find, opened https://github.com/kedacore/keda/issues/2928 - Thanks!

**Comment by v-shenoy** [comment]
@tomkerkhove @JorTurFer @zroubalik We need to create new issues for scalers that have e2e tests in `ts` in need of migration, and add them here.

**Comment by tomkerkhove** [comment]
Feel free to open them, thanks!

**Comment by v-shenoy** [comment]
Okay, I created a few. But I now realize that there's too many of them. What's the smoothest way here?

**Comment by zroubalik** [comment]
I'd create one umbrella issue, with tasks

- [ ] scaler X
- [ ] scaler Y

The task could be transferred into an issue if there's a person who is willing to contribute that.

**Comment by v-shenoy** [comment]
> I'd create one umbrella issue, with tasks
> 
> * [ ]  scaler X
> * [ ]  scaler Y
> 
> The task could be transferred into an issue if there's a person who is willing to contribute that.

Here's a list. Maybe Tom can edit and add them as a section in this issue itself. Or maybe here https://github.com/kedacore/keda/issues/2737

- [ ] ActiveMQ
- [ ] Argo Rollouts
- [ ] Artemis
- [ ] AWS CloudWatch Expression
- [ ] AWS CloudWatch (#3173)
- [ ] AWS DynamoDB
- [ ] AWS Kinesis Stream (#3171)
- [ ] AWS SQS Queue (#3172)
- [ ] Azure App Insights
- [ ] Azure Blob
- [ ] Azure Data Explorer
- [ ] Azure Log Analytics
- [ ] Azure Pipelines
- [ ] Azure Queue (Idle Replicas)
- [ ] Azure Queue (Pause At N)
- [ ] Azure Queue (Pause)
- [ ] Azure Queue (Restore Original Replicas)
- [ ] Azure Service Bus (Queue Workload Identity)
- [ ] Cassandra 
- [ ] CPU (#3169)
- [ ] Datadog
- [ ] Elastic Search
- [ ] External Scaler (ScaledJob + ScaledObject) (#3175)
- [ ] GCP PubSub (#3174)
- [ ] GCP StackDriver
- [ ] GCP Storage
- [ ] Graphite
- [ ] InfluxDB
- [ ] Kafka
- [ ] Kubernetes Workload
- [ ] Memory (#3170)
- [ ] Metrics API (Trigger Auth)
- [ ] Metrics API
- [ ] MonboDB
- [ ] MSSQL
- [ ] MySQL
- [ ] NewRelic
- [ ] OpenStack Swift
- [ ] PostgreSQL (Hashicorp) (#3176)
- [ ] PostgreSQL
- [ ] PredictKube
- [ ] Prometheus (Value Metric Type)
- [ ] Prometheus
- [ ] RabbitMQ (AMQP)
- [ ] RabbitMQ (HTTP Regex)
- [ ] RabbitMQ (HTTP Regex Vhost)
- [ ] RabbitMQ (HTTP)
- [ ] RabbitMQ (TriggerAuth)
- [ ] Redis Cluster (Lists + Streams)
- [ ] Redis (Lists + Streams)
- [ ] Redis Sentinel (Lists + Streams)
- [ ] Selenium Grid
- [ ] Solace
- [ ] Stan

**Comment by zroubalik** [comment]
Thanks!

**Comment by zroubalik** [comment]
Updated here: https://github.com/kedacore/keda/issues/2737

**Comment by tomkerkhove** [comment]
> > I'd create one umbrella issue, with tasks
> > 
> > * [ ]   scaler X
> > * [ ]   scaler Y
> > 
> > The task could be transferred into an issue if there's a person who is willing to contribute that.
> 
> Here's a list. Maybe Tom can edit and add them as a section in this issue itself. Or maybe here #2737
> 
> * [ ]  ActiveMQ
> * [ ]  Argo Rollouts
> * [ ]  Artemis
> * [ ]  AWS CloudWatch Expression
> * [ ]  AWS CloudWatch ([Migrate e2e test for AWS Cloudwatch scaler to Go. #3173](https://github.com/kedacore/keda/issues/3173))
> * [ ]  AWS DynamoDB
> * [ ]  AWS Kinesis Stream ([Migrate e2e test for AWS Kinesis Stream scaler to Go. #3171](https://github.com/kedacore/keda/issues/3171))
> * [ ]  AWS SQS Queue ([Migrate e2e test for AWS SQS Queue scaler to Go. #3172](https://github.com/kedacore/keda/issues/3172))
> * [ ]  Azure App Insights
> * [ ]  Azure Blob
> * [ ]  Azure Data Explorer
> * [ ]  Azure Log Analytics
> * [ ]  Azure Pipelines
> * [ ]  Azure Queue (Idle Replicas)
> * [ ]  Azure Queue (Pause At N)
> * [ ]  Azure Queue (Pause)
> * [ ]  Azure Queue (Restore Original Replicas)
> * [ ]  Azure Service Bus (Queue Workload Identity)
> * [ ]  Cassandra
> * [ ]  CPU ([Migrate e2e test for CPU scaler to Go. #3169](https://github.com/kedacore/keda/issues/3169))
> * [ ]  Datadog
> * [ ]  Elastic Search
> * [ ]  External Scaler (ScaledJob + ScaledObject) ([Migrate e2e test for external scaler to Go. #3175](https://github.com/kedacore/keda/issues/3175))
> * [ ]  GCP PubSub ([Migrate e2e test for Google Cloud Pub/Sub scaler to Go. #3174](https://github.com/kedacore/keda/issues/3174))
> * [ ]  GCP StackDriver
> * [ ]  GCP Storage
> * [ ]  Graphite
> * [ ]  InfluxDB
> * [ ]  Kafka
> * [ ]  Kubernetes Workload
> * [ ]  Memory ([Migrate e2e test for memory scaler to Go. #3170](https://github.com/kedacore/keda/issues/3170))
> * [ ]  Metrics API (Trigger Auth)
> * [ ]  Metrics API
> * [ ]  MonboDB
> * [ ]  MSSQL
> * [ ]  MySQL
> * [ ]  NewRelic
> * [ ]  OpenStack Swift
> * [ ]  PostgreSQL (Hashicorp) ([Migrate e2e test for Hashicorp Vault to Go. #3176](https://github.com/kedacore/keda/issues/3176))
> * [ ]  PostgreSQL
> * [ ]  PredictKube
> * [ ]  Prometheus (Value Metric Type)
> * [ ]  Prometheus
> * [ ]  RabbitMQ (AMQP)
> * [ ]  RabbitMQ (HTTP Regex)
> * [ ]  RabbitMQ (HTTP Regex Vhost)
> * [ ]  RabbitMQ (HTTP)
> * [ ]  RabbitMQ (TriggerAuth)
> * [ ]  Redis Cluster (Lists + Streams)
> * [ ]  Redis (Lists + Streams)
> * [ ]  Redis Sentinel (Lists + Streams)
> * [ ]  Selenium Grid
> * [ ]  Solace
> * [ ]  Stan

Why do we have  Argo Rollouts in the list? This is not a scaler we have today.

**Comment by JorTurFer** [comment]
yes, we use argo-rollouts to test KEDA with custom resources with /scale but we don't support scaling base on them

**Comment by tomkerkhove** [comment]
Is the above list still accurate @JorTurFer ?

**Comment by JorTurFer** [comment]
> Is the above list still accurate @JorTurFer ?

I'll check it during the day and I'll update the issue if needed

**Comment by JorTurFer** [comment]
The e2e test listed are missing and also IBM MQ and Openstack Metrics (They don't have any issue yet)

**Comment by JorTurFer** [comment]
I have just updated the description with the new issues. All the Azure Workload Identity apply also for AAD-Pod-Idendity, I have to update the issues to include both (as the tests are quite similar, we can do both at once)

**Comment by tomkerkhove** [comment]
Awesome, thanks! Do you think it makes sense splitting scalers from auth support?

I'm asking because the list gets long, while majority is just for Azure auth e2e.

**Comment by JorTurFer** [comment]
Yeah,
As the authentication code is partially part of the scaler code, I think we should have those test cases covered. I mean, for example, in azure scalers (where we use multiple SDKs) having one covered with Workload Identity doesn't guarantee that the other scalers will work. 
The only case where it can be duplicated is in scalers like servicebus where we have topics and queues, but the majority of the code is the same.
We can remove them if you think isn't worth, but I prefer to cover them, because otherwise we don't have guarantees of them (a typo could be introduced in scaler code for example, removing the pod identity support). From the e2e test duration pov, we could go more aggresive running more test together if we want to reduce the e2e test durantion
