### ISSUE TITLE
Release: v2.13.1

### ISSUE THREAD

**Issue by JorTurFer** [kedacore/keda#5504]
This issue template is used to track the rollout of a new KEDA version.

For the full release process, we recommend reading [this document](https://github.com/kedacore/keda/blob/main/RELEASE-PROCESS.md).

## Required items

- [x] https://github.com/kedacore/keda/pull/5452
- [x] https://github.com/kedacore/keda/pull/5421
- [ ] https://github.com/kedacore/keda/issues/5487
- [x] https://github.com/kedacore/keda/pull/5518
- [x] https://github.com/kedacore/keda/pull/5519

# Timeline

We aim to release this release in the week of <week range, example March 27-31>.

## Progress

- [x] Prepare changelog
- [x] [Welcome message supported versions](https://github.com/kedacore/keda/blob/main/pkg/util/welcome.go#L29-L30) are up-to-date
- [x] Add the new version to [GitHub Bug report](https://github.com/kedacore/keda/blob/main/.github/ISSUE_TEMPLATE/3_bug_report.yml) template
- [x] Best effort version bump for dependencies, example: [#5400](https://github.com/kedacore/keda/pull/5400)
  - [x] Update k8s go modules and pin to the 2nd most recent minor version
  - [x] Check if new Go has been released and if KEDA can be safely built by it
  - [x] Update linters and build pipelines if Go has been bumped, example: [#5399](https://github.com/kedacore/keda/pull/5399)
- [x] Best effort changelog cleanup, sometimes the notes can be a little inconsistent, example: [#5398](https://github.com/kedacore/keda/pull/5398)
- [x] Create KEDA release
- [x] Publish new documentation version
- [x] Setup continuous container scanning with Snyk
- [x] Prepare & ship Helm chart
- [x] Create a new issue in [KEDA OLM repository](https://github.com/kedacore/keda-olm-operator/issues/new/choose)
- [x] Prepare next release
- [x] Provide update in Slack
- [x] Tweet about new release

**Comment by tomkerkhove** [comment]
I'm happy to handle the release itself if we are looking for a release captain.

@JorTurFer We did not fill in an ETA, is that on purpose?

**Comment by JorTurFer** [comment]
> We did not fill in an ETA, is that on purpose?

Mistake, but I have no idea about the ETA either xD Next week?

**Comment by JorTurFer** [comment]
Last release was "last month" but I can't check when 😢 
I'd aim to a month and a half after the last releate

**Comment by zroubalik** [comment]
For me, the main purpose of this issue is to track issues that we might want to include, to not lost track of them.

**Comment by seddarj** [comment]
Hello, seeing issues related to what was fixed in #5452. Any ETA on when you will release 2.13.1?

**Comment by JorTurFer** [comment]
> Hello, seeing issues related to what was fixed in #5452. Any ETA on when you will release 2.13.1?

@seddarj , the the new versions has been published, KEDA v2.13.1 and for helm v2.13.2

**Comment by JorTurFer** [comment]
Release completed!
