### ISSUE TITLE
Release: 2.15

### ISSUE THREAD

**Issue by JorTurFer** [kedacore/keda#6001]
This issue template is used to track the rollout of a new KEDA version.

For the full release process, we recommend reading [this document](https://github.com/kedacore/keda/blob/main/RELEASE-PROCESS.md).

## Required items

- [x] List items that are still open, but required for this release

# Timeline

We aim to release this release in the week of Aug 1st.

## Progress

- [x] Prepare changelog
- [x] [Welcome message supported versions](https://github.com/kedacore/keda/blob/main/pkg/util/welcome.go#L29-L30) are up-to-date
- [x] Add the new version to [GitHub Bug report](https://github.com/kedacore/keda/blob/main/.github/ISSUE_TEMPLATE/3_bug_report.yml) template
- [x] Best effort version bump for dependencies, example: [#5400](https://github.com/kedacore/keda/pull/5400)
  - [x] Update k8s go modules and pin to the 2nd most recent minor version
  - [x] Check if new Go has been released and if KEDA can be safely built by it
  - [x] Update linters and build pipelines if Go has been bumped, example: [#5399](https://github.com/kedacore/keda/pull/5399)
- [x] Best effort changelog cleanup, sometimes the notes can be a little inconsistent, example: [#5398](https://github.com/kedacore/keda/pull/5398)
- [x] Create KEDA release
- [x] Publish new documentation version
- [x] Setup continuous container scanning with Snyk
- [x] Prepare & ship Helm chart
- [x] Create a new issue in [KEDA OLM repository](https://github.com/kedacore/keda-olm-operator/issues/new/choose)
- [x] Prepare next release
- [x] Provide update in Slack
- [x] Tweet about new release

**Comment by JorTurFer** [comment]
v2.15 is out :shipit: 🚀
