### ISSUE TITLE
Release: v2.16

### ISSUE THREAD

**Issue by JorTurFer** [kedacore/keda#6260]
This issue template is used to track the rollout of a new KEDA version.

For the full release process, we recommend reading [this document](https://github.com/kedacore/keda/blob/main/RELEASE-PROCESS.md).

## Required items

- [x] https://github.com/kedacore/keda/pull/6305/
- [x] https://github.com/kedacore/keda/pull/6169
- [x] https://github.com/kedacore/keda/pull/6235
- [x] https://github.com/kedacore/keda/pull/6129
- [x] https://github.com/kedacore/keda/pull/6232
- [x] https://github.com/kedacore/keda/pull/6182
- [x] https://github.com/kedacore/keda/pull/6081

## Nice to have
- [ ] https://github.com/kedacore/keda/pull/6276
- [ ] https://github.com/kedacore/keda/pull/6134
- [ ] https://github.com/kedacore/keda/pull/6230
- [ ] https://github.com/kedacore/keda/pull/6280
- [ ] https://github.com/kedacore/keda/pull/5962

# Timeline

We aim to release this release in the week of ~October 30th~ November 3rd

## Progress

- [x] Prepare changelog
- [x] [Welcome message supported versions](https://github.com/kedacore/keda/blob/main/pkg/util/welcome.go#L29-L30) are up-to-date
- [x] Add the new version to [GitHub Bug report](https://github.com/kedacore/keda/blob/main/.github/ISSUE_TEMPLATE/3_bug_report.yml) template
- [x] Best effort version bump for dependencies, example: [#5400](https://github.com/kedacore/keda/pull/5400)
  - [x] Update k8s go modules and pin to the 2nd most recent minor version
  - [x] Check if new Go has been released and if KEDA can be safely built by it
  - [x] Update linters and build pipelines if Go has been bumped, example: [#5399](https://github.com/kedacore/keda/pull/5399)
- [x] Best effort changelog cleanup, sometimes the notes can be a little inconsistent, example: [#5398](https://github.com/kedacore/keda/pull/5398)
- [x] Create KEDA release
- [x] Publish new documentation version
- [x] Setup continuous container scanning with Snyk
- [x] Prepare & ship Helm chart
- [x] Create a new issue in [KEDA OLM repository](https://github.com/kedacore/keda-olm-operator/issues/new/choose)
- [x] Prepare next release
- [x] Provide update in Slack
- [x] Tweet about new release

**Comment by JorTurFer** [comment]
Nobody has included anything to be merged before the release and I think that e2e test can be merged later on (although they aren't 100% stables, they are quite better), so the release will continue with the plan as expected.
FYI @zroubalik @wozniakjan @SpiritZhou

**Comment by wozniakjan** [comment]
nothing from me directly but if we could fix https://github.com/kedacore/keda/issues/6255, that would be great. Because if I understand correctly, July 22, 2025, the GCP pub/sub scaler will need to support the promql syntax.

**Comment by JorTurFer** [comment]
So, should we postpone the release until next week? Is anybody working on #6255?

**Comment by JorTurFer** [comment]
There are currently 41 PR and maybe there are some of them interesting, but I haven't had time to review them, during the long weekend I can review them and maybe any other can do the same, including more features if we postpone the release for a week 🤔

**Comment by SpiritZhou** [comment]
> There are currently 41 PR and maybe there are some of them interesting, but I haven't had time to review them, during the long weekend I can review them and maybe any other can do the same, including more features if we postpone the release for a week 🤔

I reviewed some of them and some simple scaler refactor PRs are OK to be merged.

**Comment by wozniakjan** [comment]
> So, should we postpone the release until next week? Is anybody working on #6255?

I don't think there is anyone working on #6255 actively, but I'm wondering if we can just add a `query` metadata field to the GCP pub/sub scaler and reuse code from the prometheus
https://keda.sh/docs/1.4/scalers/prometheus/#trigger-specification

maybe that is what you mentioned in https://github.com/kedacore/keda/issues/6255#issuecomment-2427506931?

**Comment by JorTurFer** [comment]
we are facing with issues related with docker rate limit making the e2e tests flaky:
![image](https://github.com/user-attachments/assets/68457e5d-69fd-464d-87a5-a77b88527111)

We are going to include a proxy via ACR or ECR or so, but in the meantime we decided to postpone the release to the next week

**Comment by JorTurFer** [comment]
@zroubalik @wozniakjan , The e2e tests are fixed, and I've updated the issue description with some PR/issues those would be nice to have in the release and others those I think that are required. PTAL and update the list if you think that it's wrong.

I aim to cut the release on Thursday, 7th

**Comment by JorTurFer** [comment]
Release completed!
